import pandas as pd
df = pd.read_csv('user_data.csv')
print("--- Usernames Column Only ---")
print(df['Usernames'])
print()
print("--- Second Row Data ---")
print(df.iloc[1])
print()
print("--- Sorted by Usernames (Ascending) ---")
sorted_users = df.sort_values("Usernames")
print(sorted_users)
print()
print("--- Sorted by Passwords (Descending) ---")
sorted_passwords = df.sort_values("Passwords", ascending=False)
print(sorted_passwords)